### ISSUE TITLE
Deleted Question

### ISSUE THREAD

**Issue by byronbytes** [connorads/meet-kicker#1]
Deleted Question.

**Comment by connorads** [comment]
> does this work if ur not host

**Short answer:** This is not a hack, you can only kick using this if you're allowed to kick already.

**Long answer**: It depends, according to [Pin, mute, or remove Google Meet participants
](https://support.google.com/a/users/answer/9847057?co=GENIE.Platform%3DDesktop&hl=en&oco=0)
> Meetings organized through a Google Workspace account: A participant from the domain that organized the video meeting can remove another participant, if necessary. 

> Meetings organized through a personal Google account: Only the event moderator can remotely remove another participant. 

But I think this is different for [Google Edu](https://gsuiteupdates.googleblog.com/2020/03/hangouts-meet-edu-updates.html).

**Comment by byronbytes** [comment]
Ohhhh I was hoping to find one where you could kick anyone lol

**Comment by connorads** [comment]
You're not the first person to hope that @byronbytes 🙃

I've tried to make this clearer now ...
- [Updated the Readme](https://github.com/connorads/meet-kicker/commit/c10dca4bd055ee2db5fc06789999dd955e12c47f)
- Requested update to store description
- Replied to review comment

![image](https://user-images.githubusercontent.com/10026538/98464787-fbfa8680-21bc-11eb-88ca-dbad512df8b5.png)
![image](https://user-images.githubusercontent.com/10026538/98464820-4a0f8a00-21bd-11eb-8cdb-f6e5e4ed8a89.png)
